version: "3.4"

documents:
  # Item tag below is not of any significance, purely for structure
  cumulus-netq-deployment:
    # PDF file name
    name: Cumulus-NetQ-Deployment-Guide
    # Path to the index HTML file for the title page
    title-page: cumulus-netq/Cumulus-NetQ-Deployment-Guide/title/
    # Paths to index files to include
    folders:
      - cumulus-netq/Cumulus-NetQ-Deployment-Guide/
      - cumulus-netq/Cumulus-NetQ-Deployment-Guide/NetQ-Basics/
      - cumulus-netq/Cumulus-NetQ-Deployment-Guide/NetQ-Basics/NetQ-Components
      - cumulus-netq/Cumulus-NetQ-Deployment-Guide/NetQ-Basics/DC-Deploy-Arch
      - cumulus-netq/Cumulus-NetQ-Deployment-Guide/NetQ-Basics/NetQ-Operation
      - cumulus-netq/Cumulus-NetQ-Deployment-Guide/Install-NetQ/
      - cumulus-netq/Cumulus-NetQ-Deployment-Guide/Install-NetQ/Prerequisites
      - cumulus-netq/Cumulus-NetQ-Deployment-Guide/Install-NetQ/Prepare-for-Install
      - cumulus-netq/Cumulus-NetQ-Deployment-Guide/Install-NetQ/Install-NetQ-Using-AdminUI
      - cumulus-netq/Cumulus-NetQ-Deployment-Guide/Install-NetQ/Install-NetQ-Using-CLI
			- cumulus-netq/Cumulus-NetQ-Deployment-Guide/Install-NetQ/Install-NetQ-Agents-and-CLI-on-CL
			- cumulus-netq/Cumulus-NetQ-Deployment-Guide/Install-NetQ/Install-NetQ-Agents-and-CLI-on-Ubuntu
			- cumulus-netq/Cumulus-NetQ-Deployment-Guide/Install-NetQ/Install-NetQ-Agents-and-CLI-on-RHEL
      - cumulus-netq/Cumulus-NetQ-Deployment-Guide/Backup-and-Restore-NetQ
      - cumulus-netq/Cumulus-NetQ-Deployment-Guide/Backup-and-Restore-NetQ/Backup-NetQ
      - cumulus-netq/Cumulus-NetQ-Deployment-Guide/Backup-and-Restore-NetQ/Restore-NetQ